version: '3.3'

services:
  app:
    build:
      context: .
    env_file: .env
    ports:
      - "80:80"
    restart: always
    volumes:
     - .:/var/www/html:delegated

  postgres:
    image: postgres
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data:rw
