version: '3.3'

services:
  app:
    build:
      context: .
    env_file: .env
    ports:
      - "80:80"
      - "9191:9191"
    restart: always
    volumes:
     - .:/var/www/html:delegated

  postgres:
    image: postgres
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: data
      POSTGRES_PASSWORD: data
      POSTGRES_DB: data
    volumes:
      - ./postgres/data
